### ISSUE TITLE
[Bug] only origin is being set

### ISSUE THREAD

**Issue by Baroshem** [NozomuIkuta/h3-cors#4]
Hey hey,

In my module, I am setting the default values for your package:

```ts
      origin: '*',
      methods: ['GET','HEAD','PUT','PATCH','POST','DELETE'],
      preflight: {
        statusCode: 204
      }
```

But it does not seem to work as only the origin is being set:

```
access-control-allow-origin: *
connection: close
content-length: 822
content-security-policy: base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests
content-type: text/html;charset=UTF-8
cross-origin-embedder-policy: require-corp
cross-origin-opener-policy: same-origin
cross-origin-resource-policy: same-origin
date: Sat, 15 Oct 2022 12:21:59 GMT
origin-agent-cluster: ?1
referrer-policy: no-referrer
server-timing: -;dur=0;desc="Generate"
strict-transport-security: max-age=15552000; includeSubDomains
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-powered-by: Nuxt
x-xss-protection: 0
```

Am I doing something wrong?

**Comment by Baroshem** [comment]
Reproduction, just go to https://github.com/Baroshem/nuxt-security and clone the repository. Install the packages and run the project and inspect the browser.

**Comment by nozomuikuta** [comment]
@Baroshem 

Hi, I checked your repository and it seems that my middleware works as expected and your playground is not set up for CORS testing.

There are 2 kinds of requests to which CORS-related HTTP headers: preflight request and actual request.

https://github.com/NozomuIkuta/h3-cors/blob/f224704bfe003cac67905e70c7bf35f9950d8e31/src/handler.ts#L17-L25

In your playground, preflight request is not sent from the client and neither credentials and exposed headers are set, which is why only `Access-Control-Allow-Origin` is set.

You might want to read a post about [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) for more details.

**Comment by Baroshem** [comment]
I see, it was my mistake then. Thanks @NozomuIkuta ! Closing the issue :)
